// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// flexible_reader
arma::mat flexible_reader(Rcpp::RObject data);
RcppExport SEXP _SA25204132_flexible_reader(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(flexible_reader(data));
    return rcpp_result_gen;
END_RCPP
}
// Sigma_k_cpp
arma::mat Sigma_k_cpp(const arma::mat& data, int k);
RcppExport SEXP _SA25204132_Sigma_k_cpp(SEXP dataSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(Sigma_k_cpp(data, k));
    return rcpp_result_gen;
END_RCPP
}
// FactorNum_cpp
Rcpp::List FactorNum_cpp(Rcpp::RObject data, int k0, int j0);
RcppExport SEXP _SA25204132_FactorNum_cpp(SEXP dataSEXP, SEXP k0SEXP, SEXP j0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k0(k0SEXP);
    Rcpp::traits::input_parameter< int >::type j0(j0SEXP);
    rcpp_result_gen = Rcpp::wrap(FactorNum_cpp(data, k0, j0));
    return rcpp_result_gen;
END_RCPP
}
// Loadings_Factor_cpp
Rcpp::List Loadings_Factor_cpp(Rcpp::RObject data, int k0, int j0, Rcpp::Nullable<Rcpp::IntegerVector> r);
RcppExport SEXP _SA25204132_Loadings_Factor_cpp(SEXP dataSEXP, SEXP k0SEXP, SEXP j0SEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k0(k0SEXP);
    Rcpp::traits::input_parameter< int >::type j0(j0SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(Loadings_Factor_cpp(data, k0, j0, r));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA25204132_flexible_reader", (DL_FUNC) &_SA25204132_flexible_reader, 1},
    {"_SA25204132_Sigma_k_cpp", (DL_FUNC) &_SA25204132_Sigma_k_cpp, 2},
    {"_SA25204132_FactorNum_cpp", (DL_FUNC) &_SA25204132_FactorNum_cpp, 3},
    {"_SA25204132_Loadings_Factor_cpp", (DL_FUNC) &_SA25204132_Loadings_Factor_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA25204132(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
