# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

flexible_reader <- function(data) {
    .Call('_SA25204132_flexible_reader', PACKAGE = 'SA25204132', data)
}

Sigma_k_cpp <- function(data, k) {
    .Call('_SA25204132_Sigma_k_cpp', PACKAGE = 'SA25204132', data, k)
}

#' @title Calculating the numbers of factors with Rcpp
#' @description Rcpp version of \code{FactorNum}. See more in \code{FactorNum}.
#' @param data a data frame or matrix 
#' @param k0 a pre-specified integer used in calculating covariance matrix. The exact value won't affect the result much and it could be proper to choose it as 5(the default value) in practice.
#' @param j0 a pre-specified integer representing the maximum of the number of factors. It must be less than the number of variables. The default value is one forth of the number of variables(rounded down to the nearest integer).
#' @return a list consists of \code{r0}, \code{r}, \code{R} and \code{tao}. \code{r0} is the number of common factors. \code{r} is the number of specific factors. \code{R} is all the ratios of eigenvalue sums. \code{tao} is the indices of local maximums of R, which is sorted into descending order by the corresponding value of R.
#' @examples
#' \dontrun{
#' data(CSI300_2)
#' nums <- FactorNum_cpp(CSI300_2)   
#' cat(c(nums$r0, nums$r))
#' }
#' @export
FactorNum_cpp <- function(data, k0 = 5L, j0 = -1L) {
    .Call('_SA25204132_FactorNum_cpp', PACKAGE = 'SA25204132', data, k0, j0)
}

#' @title Calculating the loading matrices of factors with Rcpp
#' @description Rcpp version of \code{Loadings_Factor}. See more in \code{Loadings_Factor}.
#' @param data a data frame or matrix 
#' @param k0 a pre-specified integer used in calculating the numbers of factors. It works only when r is \code{NULL}.
#' @param j0 a pre-specified integer used in calculating the numbers of factors. It works only when r is \code{NULL}.
#' @param r the numbers of factors. The first value is the numbers of common factors and the second value is the numbers of specific factors. When r is \code{NULL}, the function \code{FactorNum} will be used to calculate the numbers of the factors.
#' @return a list consists of \code{Loadings_CommonFactor} and \code{Loadings_SpecificFactor}, which represent the loadings of common factors and specific factors, respectively.
#' @examples
#' \dontrun{
#' data(CSI300_2)
#' Loadings_Factor_cpp(CSI300_2)   
#' }
#' @export
Loadings_Factor_cpp <- function(data, k0 = 5L, j0 = -1L, r = NULL) {
    .Call('_SA25204132_Loadings_Factor_cpp', PACKAGE = 'SA25204132', data, k0, j0, r)
}

